---
name: multi-source-synthesis
description: Generate cross-source synthesis documents from vault content. Triggers on phrases like "synthesize the marketing cluster," "consolidate the substrate sources," "create a synthesis of," "pull together what we've learned about," "give me a synthesis," "synthesize for client X," "generate a strategy for client X based on cluster Y," "cross-cluster synthesis," "pattern synthesis," "create a strategy doc," or any operator request to consolidate evidence across multiple vault sources into a single reference document. Covers four synthesis shapes (cluster, pattern, cross-cluster, client-driven) with shape-specific filing destinations. Invokes meta-document-primer skill by default to produce companion reading guide; invokes plain-language-translation skill on operator request. Defers client-profile creation as separate prerequisite operator-work.
---

# Multi-Source Synthesis Skill (v1.0)

The multi-source synthesis skill. Generates synthesis documents that consolidate evidence across multiple vault sources into a single reference. Companion infrastructure (reading guide + optional plain-language variant) is generated by invoking the meta-document-primer and plain-language-translation skills.

**Critical behavior (read this before anything else):**
- **Shape-and-destination confirmation gate is mandatory.** Skill 3 always asks the operator to confirm the synthesis shape and filing destination BEFORE drafting. Different shapes produce different output structures and file in different folders; getting this wrong wastes operator-attention.
- **Skill 3 summarizes pattern math; it does NOT promote.** Synthesis documents capture current pattern-promotion state (1/3, 2/3, 3/3) but never trigger promotions. Promotion math is vault-curation discipline; see Skill 2.
- **Companion skills are invoked from this skill; their gates are passed through to operator.** When Skill 3 invokes meta-document-primer or plain-language-translation, those skills run their own approval gates with the operator. Skill 3 does not filter or override those gates.
- **Multi-turn collaboration mode is available and recommended for substantial syntheses.** This skill supports single-agent mode (one agent does everything) and multi-turn mode (executor agent + review agent + operator collaboration). See "Multi-turn collaboration protocol" below for when to use which.
- **Skill 3 is the structured path for synthesis; it is not the only path.** Ad-hoc synthesis work (e.g., a quick consolidation of 2-3 sources for a one-off operator-strategic decision) may be done outside this skill via operator-prompted Cowork tasks. The Phase B synthesis at `_meta/synthesis/phase-b-synthesis-2026-05-10.md` was created ad-hoc before this skill existed and remains canonical. Use Skill 3 when the synthesis warrants structured shape-and-destination discipline + companion skill invocations; use ad-hoc Cowork prompts for lightweight one-off consolidations.

## Multi-turn collaboration protocol

This skill supports multi-agent collaboration as a first-class mode alongside single-agent execution. The role definitions and dance protocol are agent-agnostic; the current configuration is typically Cowork as executor + web-UI Claude as review agent + Oliver as operator.

### Role definitions (agent-agnostic)

- **Executor agent** — the agent that does the actual file operations: reads vault content (sources, tactics, patterns, tools, primer), drafts the synthesis document, writes the file, invokes companion skills (meta-document-primer, plain-language-translation), reports completion. Makes synthesis calibration decisions during execution (not blind execution; the executor reads relevant vault state, applies synthesis-discipline precedents, surfaces judgment calls at the shape-and-destination gate). In current configuration this is typically Cowork.
- **Review agent** — the agent the operator collaborates with to draft Skill 3 invocation prompts, validate executor's draft synthesis when operator surfaces it, pressure-test calibration decisions, recommend revisions. Does NOT execute file operations directly. In current configuration this is typically a web-UI Claude chat.
- **Operator** — the human in the loop. Decides at the shape-and-destination confirmation gate, decides whether to invoke companion skills, reviews the final synthesis in Obsidian (or downloads from outputs in web-UI environments), commits manually.

The skill's behavior depends on what configuration is invoking it. If the executor is invoking directly (no review agent in the loop), it follows the "single-agent mode" path. If the executor is being driven by a review agent + operator combination, it follows the "multi-turn mode" path.

### When to use which mode

**Single-agent mode is appropriate when:**
- One-off synthesis request with clear shape (operator already knows it's a cluster synthesis of cluster X)
- Cluster has reached operational stability with clear pattern-math state (less calibration pressure)
- Operator-attention budget is constrained
- Speed matters more than rigorous calibration pressure-testing

**Multi-turn mode is appropriate when:**
- Cross-cluster synthesis (scope spans multiple clusters; calibration decisions affect multiple domains)
- Client-driven synthesis (client-deliverable; correctness matters operationally)
- Synthesis touches sources where pattern-math state is contested or near-threshold
- Operator wants pressure-testing of executor's evidence-filtering decisions
- The synthesis will be referenced extensively by downstream agents or build-plan work

**Operator-attention budget reality check:** Synthesis is more concentrated work than extraction. A single cluster synthesis on 5-10 sources is typically a 30-90 minute operator-attention session (vs ingestion's variable per-source rhythm). Multi-turn mode adds transcription overhead but produces better calibration on contested decisions. Budget accordingly.

### Single-agent mode workflow

When invoked without a review agent in the loop:

1. Executor receives operator's synthesis request
2. Executor analyzes request and proposes synthesis shape + destination + variants
3. Executor surfaces proposal to operator at shape-and-destination gate
4. Operator confirms or modifies
5. Executor drafts synthesis
6. Executor writes synthesis file to confirmed destination
7. Executor invokes meta-document-primer skill (default-on) on the synthesis
8. If plain-language variant requested: executor invokes plain-language-translation skill on the synthesis
9. Executor reports completion with all files created
10. Operator reviews / commits manually

This is the standard standalone path. Use when there's no review agent in the loop.

### Multi-turn mode workflow

When a review agent is present, the work flows through phases per source. Transcription is the dominant cost driver of multi-turn mode.

#### Phase A — Request analysis and prompt drafting

- Operator provides synthesis request to review agent (e.g., "synthesize the marketing cluster" or "create a strategy for EV Electric Services based on the marketing cluster")
- Review agent analyzes request and drafts Skill 3 invocation prompt for executor agent including: synthesis intent, recommended shape (with reasoning), recommended destination, recommended variants (primer default-on; plain-language operator-choice), relevant vault context the executor should read (cluster sources, pattern math state, client profile if applicable), discipline reminders
- Operator transcribes prompt from review agent to executor agent

#### Phase B — Shape-and-destination confirmation

- Executor reads relevant vault context per Skill 3 invocation prompt
- Executor proposes synthesis shape + destination + variants with reasoning at shape-and-destination gate
- Operator transcribes proposal from executor to review agent
- Review agent pressure-tests proposal; surfaces concerns if shape misfit, destination wrong, variants over/under-scoped
- Operator transcribes review agent's assessment back to executor (approve / modify / reject)

#### Phase C — Synthesis drafting and writing

- Executor drafts synthesis per confirmed shape
- Executor writes synthesis file to confirmed destination
- Executor reports completion of write to operator with synthesis-file-path
- Operator transcribes write-completion to review agent
- Review agent validates that synthesis matches shape expectations; flags substantive issues if present
- Operator transcribes review agent assessment to executor (proceed to companion skills / pause for revision)

#### Phase D — Companion skill invocations

- Executor invokes meta-document-primer skill on the just-written synthesis (default-on per critical-behavior callout above)
- Meta-document-primer skill runs its own workflow; surfaces approval gates directly to operator (NOT filtered through Skill 3 or executor)
- If operator requested plain-language variant: executor invokes plain-language-translation skill on the synthesis after meta-document-primer completes
- Plain-language-translation skill runs its own workflow; surfaces its own gates if any directly to operator
- Executor reports completion of all companion skill invocations

#### Phase E — Completion report and commit handoff

- Executor produces final completion report listing all files created (synthesis + reading guide + optional plain-language variant + any master-primer extensions)
- Operator transcribes completion report to review agent
- Review agent drafts commit message preserving synthesis decision archaeology (shape choice, destination choice, variant choices, evidence sources synthesized)
- Operator commits manually using heredoc-to-file pattern (see Skill 1 Chunk 5 commit message template)

### Why this protocol exists

Synthesis is calibration-heavy work. The shape-and-destination decision determines what the synthesis is FOR; getting it wrong produces a document that doesn't serve operator-purpose. Multi-turn mode catches shape-misfit and destination-misfit at the proposal gate before drafting begins. Single-agent mode is faster but relies on executor calibration without external pressure-testing; appropriate for clear-shape synthesis requests but risky for contested calibration.

### Mode switching mid-synthesis

The operator may need to switch modes within a single synthesis run. Most common case: Phase A-B ran in single-agent mode (operator running executor directly) but operator wants Phase C synthesis drafting review with a review agent in the loop because the synthesis draft surfaced contested calibration.

To switch into multi-turn mid-synthesis: operator copies executor's current state output to review agent + tells review agent which phase the executor stopped at. Review agent picks up from that point with appropriate context.

To switch out of multi-turn mid-synthesis: operator tells executor "skip the review-agent loop for the remainder of this synthesis; complete writing + companion-skill invocations with standard discipline; default to conservative choices when in doubt."

### Fresh-context discipline for synthesis review agent

Synthesis is one of the higher-context-cost operations a review agent can do. A review agent doing synthesis pressure-testing typically needs to hold in context: the cluster sources (5-10 source notes worth of material), the relevant tactic notes, the relevant pattern notes, the master primer, current goals, build plan, and the synthesis draft itself.

Synthesis work typically consumes meaningfully more context than per-source extraction, because the review agent holds the entire cluster (sources + tactics + patterns + cross-references) in working memory simultaneously rather than processing one source at a time. Cluster size matters but isn't the only factor — a 10-source cluster with dense pattern-math interactions may consume more review-agent attention than a 25-source cluster with sparse interactions.

There's no fixed source-count threshold for when synthesis review-agent context fatigue kicks in. Watch for the symptoms (below) and refresh context when they appear, regardless of where the source count happens to be. Plan accordingly: dedicate a review agent chat to a single synthesis OR a small batch of related syntheses; don't try to do 3+ syntheses in one review agent chat without fresh-context refresh.

Symptoms of synthesis review agent context fatigue:
- Review agent starts repeating itself across synthesis-draft assessments
- Review agent's pressure-testing becomes less specific to current synthesis draft
- Review agent loses track of which cluster sources are which
- Review agent's prompt drafts for executor become more generic

When these symptoms appear, open a fresh review agent chat. Seed the new chat with synthesis-specific context (described below).

### Project knowledge management for synthesis review agent

The synthesis review agent's quality depends on what's in its project knowledge. Different from extraction review agent's project knowledge requirements:

**Always include:**
- `_meta/current-goals.md` — operator-level goals + relevance calibration
- `_meta/scoring-rubric.md` — canonical scoring definitions
- `_meta/primers/primer-synthesis-vocabulary-and-concepts.md` — master primer (Part 1 + Appendix A)
- Active build plan document if relevant (e.g., `goal-a-expanded-build-plan.md`)
- `01_ai-operating-system/master-system-map.md` — architectural context

**Include for cluster synthesis:**
- All source notes in the target cluster (typically 5-10 files)
- All tactic notes in the target cluster
- All tool notes the cluster references
- Existing synthesis documents from the target cluster if any (rare for new clusters)

**Include for pattern synthesis:**
- The pattern note being synthesized
- All sources contributing to the pattern (per the pattern's sources-array)
- Adjacent patterns (in the same sub-layer or with shared mechanism)
- Pattern math state from the most recent vault-wide pattern-landscape document (`phase-b-synthesis-2026-05-10.md` is the current canonical reference)

**Include for cross-cluster synthesis:**
- Cluster summaries for each cluster spanned (don't load all sources from each cluster; load cluster MOCs or the most representative 2-3 sources per cluster)
- Sample pattern notes from each cluster
- The operator-strategic question or decision the synthesis is anchored to
- Phase B synthesis as exemplar (`phase-b-synthesis-2026-05-10.md`)

**Include for client-driven synthesis:**
- The client's README profile at `04_projects/clients/_active/<client-slug>/README.md` (PREREQUISITE — if absent, synthesis cannot proceed)
- Cluster summaries for clusters the synthesis will pull from
- Operator's `_strategic-decisions/` folder contents (operator-discipline context that affects client work)
- Relevant tactic notes (filtered by client-relevance, not full cluster dumps)

**Don't include:**
- All vault source notes (too much; executor handles per-source detail)
- All pattern notes (too much; executor handles)
- Unrelated cluster content (synthesis stays focused on its actual scope)

The principle: upstream-context + master-primer + scoped vault content for the specific synthesis. Not a full vault replica. Aim for ~15-25 files in project knowledge for substantial syntheses, weighted toward the specific cluster/pattern/client the synthesis is about.

### What the synthesis review agent SHOULD do

- Draft well-structured Skill 3 invocation prompts for executor with all relevant context
- Pressure-test executor's shape-and-destination proposal honestly (don't rubber-stamp; don't manufacture objections)
- Verify pattern math state is being summarized correctly (not promoted)
- Surface evidence-filtering concerns for client-driven syntheses (HVAC client shouldn't get video-cluster evidence)
- Surface contradiction-handling concerns for cluster syntheses (creators disagree; how does synthesis present the disagreement)
- Verify synthesis shape matches operator-intent
- Recognize own context fatigue and surface it to operator before review-quality degrades

### What the synthesis review agent SHOULD NOT do

- Execute file operations directly (that's the executor's role)
- Draft the synthesis document itself (that's the executor's role; review agent shapes prompts and reviews outputs)
- Override operator decisions at approval gates
- Filter or override the meta-document-primer skill's gates when it's invoked (those gates are between operator and meta-document-primer skill directly)
- Filter or override the plain-language-translation skill's behavior when invoked
- Continue past stop-conditions in this skill or in invoked companion skills

### What the operator's role looks like

The operator's role in multi-turn synthesis is primarily decisional + transcriptive:

- Decides at shape-and-destination confirmation gate
- Decides whether to request plain-language variant
- Approves at meta-document-primer skill's own gates (passed through from invoked skill)
- Transcribes prompts/outputs between agents (review agent ↔ executor agent)
- Reviews final synthesis in Obsidian / downloads from outputs
- Commits manually after synthesis + companion files all complete
- Decides when to switch between single-agent and multi-turn modes (mid-synthesis or per-synthesis)
- Decides when to refresh review agent's context (open fresh chat)

The operator does NOT need to validate every word of the synthesis draft — that's not the synthesis review agent's job either. Both review agent and operator focus on calibration correctness (shape fit, destination fit, evidence filtering, pattern math state, contradiction handling); fine-grained content review happens after the synthesis is written and operator reads the actual file in Obsidian.

## Invocation workflow

Skill 3 follows a fixed invocation workflow regardless of mode. The workflow has six stages:

### Stage 1 — Receive operator request

Operator invokes the skill with a request. Common request shapes:

**Cluster-synthesis shape (most common):**
- "Synthesize the marketing cluster"
- "Consolidate the substrate sources"
- "Pull together what we've learned about content-creation"

**Pattern-synthesis shape:**
- "Synthesize the agent-substrate-as-MCP-backend pattern"
- "Consolidate evidence on cross-substrate independent arrival"

**Cross-cluster shape:**
- "What does marketing + content cluster evidence collectively suggest for marketing-PM agent worker repertoire?"
- "Cross-cluster synthesis on AI-augmented small-business growth tactics"

**Client-driven shape:**
- "Based on client EV Electric Services, help me pull from marketing + content clusters to give them an X result"
- "Create a strategy for client S&H Contracting that gets them their stated outcome based on their profile"

If the request doesn't fit any clear shape, ask operator at Stage 2 to specify.

### Stage 2 — Analyze request and propose shape + destination + variants

The executor reads the operator's request and proposes shape + destination + variants based on the request's signals. The executor also verifies preconditions before producing a proposal; if preconditions fail, the executor produces a blocked-on-precondition response instead.

**Precondition checks (run before proposal):**

For cluster synthesis:
- Target cluster has 5+ source notes filed (rough threshold; below this the cluster is too thin for meaningful synthesis)
- Most sources are operator-approved and triaged (extracted → triaged status; in-inbox sources may not yet have operator-approved scope)
- Pattern math state is current (no recent retroactive corrections pending that would change pattern attributions)

For pattern synthesis:
- Pattern is at threshold (3/3) OR pattern has reached 2/3 with operational utility (1/3 patterns are typically too thin for synthesis)
- Pattern's sources-array is current and verified
- Pattern note has cross-references to all canonical creators correctly attributed

For cross-cluster synthesis:
- Operator-strategic question is articulated clearly (synthesis without anchor question produces generic output)
- At least 2 clusters each at operational stability (5+ sources)
- Operator can articulate what they'd DO with the synthesis (informs scope; otherwise too speculative)

For client-driven synthesis:
- Client README profile exists at `04_projects/clients/_active/<client-slug>/README.md`
- Client profile contains: client name, business type, current state, desired outcome, constraints, timeline
- Operator can name the specific outcome they want the synthesis to drive toward

If any precondition fails, the executor surfaces the failure honestly INSTEAD OF producing a proposal:

```
Skill 3 invocation BLOCKED on precondition failure.

Failed precondition: <specific precondition>
Required: <what's needed>
Suggested remediation: <what operator should do before re-invoking>

Skill 3 will NOT proceed until precondition is resolved.
```

The most common precondition failure is client-driven synthesis without a client README. Suggested remediation: operator creates the README first (manually or via operator-prompted Cowork task), then re-invokes Skill 3.

**Shape proposal logic (when preconditions pass):**

- Request names a specific cluster → cluster synthesis
- Request names a specific pattern → pattern synthesis
- Request names a specific client (by slug or name) → client-driven synthesis
- Request asks operator-strategic question spanning multiple domains → cross-cluster synthesis
- Request is ambiguous → ask operator to clarify

**Destination proposal logic:**

- Cluster synthesis → `03_domains/<cluster>/cluster-synthesis-<cluster>-<date>.md` (filed at cluster-folder root, NOT in the `insights/` subfolder; synthesis is cluster-level while sources live in `insights/`)
- Pattern synthesis → `05_shared-intelligence/patterns/pattern-synthesis-<pattern-name>-<date>.md`
- Cross-cluster synthesis → `_meta/synthesis/cross-cluster-synthesis-<topic>-<date>.md`
- Client-driven synthesis → `04_projects/clients/_active/<client-slug>/client-synthesis-<client-slug>-<topic>-<date>.md`

**Variant proposal logic:**

- meta-document-primer skill: DEFAULT-ON for every synthesis (primers are forward-looking infrastructure; future agents will read the synthesis and need the reading guide)
- plain-language-translation skill: OPERATOR-CHOICE; default no; ask at this stage if request didn't specify

**Proposal format (surface to operator at confirmation gate):**

```
SYNTHESIS PROPOSAL

Based on your request: "<verbatim request>"

Shape: <cluster | pattern | cross-cluster | client-driven>
Reasoning: <one paragraph why this shape fits>

Destination: <full path to synthesis file>
Reasoning: <one sentence on filing convention>

Companion skills:
- meta-document-primer: WILL BE INVOKED (default-on; produces reading guide in _meta/primers/readings/)
- plain-language-translation: <WILL BE INVOKED if operator requested | WILL NOT BE INVOKED by default — operator can request>

Scope:
- <list of source notes / tactic notes / pattern notes / client profile that will be synthesized>
- <approximate scope size in human terms>

Confirm / modify / reject?
```

**Scope-listing discipline:**

- For small scope (≤10 sources): enumerate sources individually by wikilink for operator review
- For medium scope (10-20 sources): enumerate with summary counts ("12 sources in marketing cluster filed between 2026-05-13 and 2026-06-15, full list below") + collapsed source list
- For large scope (20+ sources): summary description only ("all 27 source notes in `03_domains/marketing/insights/`"; "all sources contributing to `[[tactic-X]]`'s sources-array (12 creators)"); skip enumeration; operator can request enumeration if needed
- Always include tactic/pattern note count separately from source count (operator may want to spot-check pattern coverage)
- Always include any specific exclusions explicitly ("excludes 3 sources flagged for cluster-correction; see decision archaeology")

### Stage 3 — Operator confirms or modifies

Operator response:

- **Confirm**: proceed to Stage 4
- **Modify shape**: re-propose with operator-specified shape; loop back to Stage 2 if substantial change
- **Modify destination**: update destination; proceed to Stage 4
- **Add plain-language variant**: include in companion-skill invocations; proceed to Stage 4
- **Modify scope**: adjust scope (add/remove sources, expand/narrow cluster boundaries); re-propose; loop back to Stage 2 if substantial change
- **Reject**: stop; do not write

### Stage 4 — Draft synthesis

Executor drafts the synthesis per confirmed shape. Synthesis-document structure is shape-specific; see Chunk 4 of this skill for shape-specific templates (forward reference; Chunk 4 will document the templates).

Drafting discipline:

- Use master primer (`_meta/primers/primer-synthesis-vocabulary-and-concepts.md`) as authoritative for shared vocabulary; don't redefine concepts the master primer already covers
- Cite pattern math state precisely (1/3, 2/3, 3/3 with creator attributions) but don't promote
- For cluster syntheses: handle contradictions between creators honestly; present disagreement rather than papering over
- For client-driven syntheses: filter evidence by client-relevance per the client profile; don't dump unrelated cluster evidence
- Preserve wikilinks to all source notes, tactic notes, tool notes, and pattern notes referenced; vault-navigation depends on them
- Preserve operator-discipline precedent references (cross-creator counting rules, Karpathy-weight, cross-substrate independent arrival, etc.) with cross-reference to Skill 2 OR to the master primer's Section G
- Use date-of-synthesis in the filename per naming convention (cluster-synthesis-<cluster>-<date>.md etc.); use ISO date format (YYYY-MM-DD)

### Stage 5 — Write synthesis file

Executor writes the synthesis file to confirmed destination. Frontmatter conventions:

```yaml
---
type: synthesis
synthesis-shape: <cluster | pattern | cross-cluster | client-driven>
status: draft
created: <YYYY-MM-DD>
updated: <YYYY-MM-DD>
related: [<wikilinks to sources, tactics, patterns, clusters, clients, primers>]
tags: [synthesis, <shape-specific-tags>]
---
```

If executing in a sandbox environment where the vault path isn't directly writable, write to `/mnt/user-data/outputs/` and use `present_files` to surface for operator download.

### Stage 6 — Invoke companion skills

After synthesis file is written, executor invokes companion skills:

1. **Invoke meta-document-primer skill** on the synthesis file. The invoked skill:
   - Reads the synthesis
   - Identifies gaps relative to the master primer (Step 5 of meta-document-primer)
   - May extend the master primer if gaps warrant (Step 7 of meta-document-primer, with its own operator approval gate)
   - Generates a reading guide in `_meta/primers/readings/` (Step 8 of meta-document-primer)
   - Surfaces its own gates and reports to operator directly
   - Skill 3 does NOT filter or override these gates

2. **If operator requested plain-language variant**: invoke plain-language-translation skill on the synthesis file. The invoked skill:
   - Reads the synthesis
   - Produces a plain-language version as a sibling file with `-plain` suffix
   - Surfaces its output to operator directly

3. Executor produces a completion report listing all files created:
   - Synthesis file (path)
   - Reading guide (path; from meta-document-primer)
   - Master primer extensions if any (per meta-document-primer's report)
   - Plain-language variant if requested (path; from plain-language-translation)
   - Operator next-steps (review in Obsidian, commit manually)

## Four synthesis shapes

Skill 3 produces four distinct synthesis shapes, each with different scope, inputs, output structure, and filing destination. The shape proposal at Stage 2 selects one. This section documents each shape in depth.

### Cluster synthesis

**When applies.** A single vault cluster (e.g., marketing, content/video-intelligence, automation-systems) has reached operational stability with multiple source notes filed, and operator wants to consolidate what the cluster collectively says. Most common synthesis shape after the first 5-10 sources land in a new cluster.

**Operator intent:** "Pull together what we've learned about <cluster topic>." The synthesis becomes the canonical reference for that cluster's current state.

**Inputs needed:**
- All source notes in the target cluster (typically located at `03_domains/<cluster>/insights/`)
- All tactic notes in the cluster (typically at `03_domains/<cluster>/insights/tactic-*.md` or `05_shared-intelligence/patterns/` for cross-cluster tactics)
- All tool notes the cluster references (typically at `05_shared-intelligence/tools/`)
- Pattern math state for any patterns the cluster contributes to (1/3, 2/3, 3/3 with creator attributions)
- Master primer for shared vocabulary (`_meta/primers/primer-synthesis-vocabulary-and-concepts.md`)
- Cluster-specific operator context (e.g., for marketing cluster, the Goal B framing; for content cluster, the relevant content-cluster goal framing)

**Output structure (high-level; detailed templates in Chunk 4):**
- Executive summary (cluster's overall yield, key patterns, key tactics, key decisions surfaced)
- Pattern math state (which patterns reached threshold via this cluster, which are at 2/3 awaiting cross-creator convergence, which are at 1/3)
- Tactical convergences (patterns multiple creators agree on)
- Tactical divergences (where creators disagree; preserve disagreement rather than papering over)
- Operator-actionable takeaways (what the cluster collectively suggests operator should DO)
- Open questions surfaced (decisions the cluster brings into focus without resolving)
- Cross-cluster connections (if the cluster touches adjacent clusters)
- Audit-pass items if applicable (consolidation candidates, count discrepancies, etc.)

**Filing destination:** `03_domains/<cluster>/cluster-synthesis-<cluster>-<date>.md`

Filed at cluster-folder root, NOT in `insights/` subfolder. Synthesis is cluster-level; source notes live in `insights/`. The cluster-folder root may also contain other cluster-level artifacts (cluster MOC if one exists, cluster README if scaffolded).

**Discipline-specific notes:**
- A cluster synthesis is operator-strategic-altitude, not source-detail-altitude. Don't re-summarize every source; reference sources by wikilink and synthesize themes.
- Pattern math state is summarized, not promoted. If the synthesis surfaces that a pattern has reached 3/3 via this cluster, note it explicitly but don't trigger the promotion ritual (that's vault-curation discipline; Skill 2).
- Contradictions between creators get preserved. If three sources advocate Approach A and two advocate Approach B, the synthesis presents both with evidence weights rather than collapsing to one.
- Operator-relevance is the lens. If a cluster source surfaces evidence the operator isn't acting on (e.g., substrate-tutorial-archive sources), de-emphasize in synthesis but don't omit entirely.

**Phase B exemplar:** As of this skill's creation (2026-05-13), no pure cluster synthesis exists in vault that this author is aware of (Phase B synthesis is cross-cluster-shape; see below). The first cluster synthesis to land will become the exemplar for future cluster syntheses.

### Pattern synthesis

**When applies.** A specific pattern has reached threshold (3/3 cross-creator) OR has reached 2/3 with operational utility, and operator wants to consolidate everything known about that pattern across all its contributing sources. Less common than cluster synthesis but high-value for patterns that anchor multiple downstream decisions.

**Operator intent:** "Synthesize what we know about <pattern X>." The synthesis becomes the deep-reference for that pattern, supplementing the pattern's tactic note (which is usually shorter and more operator-actionable than a full synthesis).

**Inputs needed:**
- The pattern note itself (typically at `05_shared-intelligence/patterns/<pattern-name>.md` or `03_domains/<cluster>/insights/tactic-<pattern-name>.md`)
- All sources in the pattern's sources-array (each canonical creator's source note)
- Pattern's full attribution history (canonical creators, synthesizer creators noted, originator-lineage references)
- Adjacent patterns (patterns with shared mechanism or in the same sub-layer)
- Cross-references to operator-discipline precedents the pattern interacts with (e.g., cross-creator counting, Karpathy-weight, cross-substrate independent arrival)
- Master primer for shared vocabulary

**Output structure (high-level; detailed templates in Chunk 4):**
- Pattern definition and architectural commitment (what the pattern IS)
- Cross-creator evidence summary (which canonical creators, what they each contributed)
- Pattern's etiology (originator lineage if any, how it reached threshold, retroactive-correction history if applicable)
- Mechanism analysis (the underlying mechanism that makes the pattern work across contexts)
- Variants and sub-patterns (different ways the pattern manifests)
- Composition with other patterns (which patterns this composes with, which it conflicts with)
- Operator-actionable implications (what adopting this pattern means for operator's work)
- Open questions specific to this pattern

**Filing destination:** `05_shared-intelligence/patterns/pattern-synthesis-<pattern-name>-<date>.md`

Filed adjacent to the pattern's tactic note (the pattern note itself stays at `tactic-<pattern-name>.md`; the synthesis is its deeper companion).

**Discipline-specific notes:**
- Pattern synthesis assumes the pattern is at threshold or near-threshold. Synthesizing 1/3 patterns is premature — the evidence is too thin for synthesis to add value beyond what the tactic note already captures.
- Don't conflate the pattern note (operator-actionable summary) with the pattern synthesis (deeper reference). They serve different audiences and operational purposes.
- If the pattern has retroactive corrections in its history, the synthesis is the canonical place to document the correction reasoning (the tactic note's body may also mention it, but the synthesis is where the full archaeology lives).
- Pattern synthesis should reference the master primer's Section E (cross-creator counting mechanic) rather than re-explaining it.

**Phase B exemplar:** As of this skill's creation (2026-05-13), no standalone pattern synthesis exists in vault that this author is aware of. The first pattern synthesis to land becomes the exemplar. Likely candidates for first pattern synthesis: `agent-substrate-as-mcp-backend-for-other-agents` (the first cross-substrate-independent-arrival pattern) or `context-engineering-discipline` (5-layer framework spanning multiple creators).

### Cross-cluster synthesis

**When applies.** Operator-strategic question spans multiple clusters and needs cross-cluster evidence. Less common than cluster synthesis but operationally critical when it applies. The Phase B synthesis is the canonical example.

**Operator intent:** "Given my strategic question X, pull from clusters A, B, C to consolidate what the evidence says." The synthesis becomes operator-decision-architecture-adjacent material.

**Inputs needed:**
- An operator-strategic anchor question (synthesis without anchor question produces generic output)
- Cluster summaries for each cluster spanned (don't load all sources from each cluster; load 2-3 most representative sources per cluster + any cluster synthesis if one exists)
- Pattern math state for any patterns that cross the relevant clusters
- Relevant operator-discipline precedents the synthesis touches
- Master primer for shared vocabulary
- Any prior operator-strategic documents this synthesis builds on (e.g., for Goal A work, the build plan; for substrate decisions, the closed ToS task and substrate baseline commit)

**Output structure (high-level; detailed templates in Chunk 4):**
- Executive summary (strategic question + evidence weight + key tensions)
- Cluster contributions (what each cluster brings to the question)
- Cross-cluster pattern evidence (patterns that emerge across clusters; cross-substrate independent arrival is one example)
- Tensions and contradictions (where clusters disagree or pull in different directions)
- Operator-decision space (decisions the synthesis surfaces; pros + cons + dependencies)
- Operator-discipline precedents in play (which precedents constrain interpretation)
- Audit-pass items if applicable (drift, count discrepancies, retroactive-correction candidates)
- What the synthesis does NOT decide (deliberate scope limits; operator-decision held in reserve)

**Filing destination:** `_meta/synthesis/cross-cluster-synthesis-<topic>-<date>.md`

Uses the existing `_meta/synthesis/` folder where Phase B synthesis lives. Operator-strategic cross-cluster synthesis is sufficiently high-altitude that it warrants its own folder rather than being filed under any single cluster.

**Discipline-specific notes:**
- The operator-strategic anchor question is load-bearing. Without it, the synthesis becomes a generic dump across clusters that serves no specific decision. Demand the anchor question at Stage 2.
- Cross-cluster synthesis is the right place to surface tensions across operator's work (e.g., Goal A substrate priorities vs Goal B client work timelines; agent-architecture decisions vs marketing-PM-agent worker repertoire shape).
- Phase B synthesis at `_meta/synthesis/phase-b-synthesis-2026-05-10.md` is the canonical exemplar. Match its altitude (operator-strategic), its honesty about uncertainty (6 OPEN decisions surfaced; no analysis), and its preservation of audit-pass items.
- Cross-cluster synthesis is the natural input to build-plan revisions (Skill 4 work) and major operator-strategic decisions.

**Phase B exemplar:** `_meta/synthesis/phase-b-synthesis-2026-05-10.md` — 550+ line synthesis spanning substrate cluster + Obsidian-with-AI cluster + content cluster + 10 operator-discipline precedents + 6 OPEN decisions + 8 audit-pass items. Use as structural reference for future cross-cluster syntheses.

### Client-driven synthesis

**When applies.** Operator has an active client with a documented profile, and operator wants to pull vault evidence into a client-deliverable strategy or roadmap document. Triggered by phrases like "create a strategy for client X based on cluster Y" or "based on client Z's profile, help me get them their stated outcome."

**Operator intent:** "Use my vault as the evidence base to drive client X toward their stated outcome." The synthesis becomes client-deliverable artifact (or operator-internal pre-deliverable that shapes what gets shipped to client).

**Inputs needed:**
- **Client README profile at `04_projects/clients/_active/<client-slug>/README.md`** (PREREQUISITE — if absent, synthesis cannot proceed)
- The full README is read; the skill makes NO assumption about specific field names or required structure within the README. Operator may organize the README as they prefer (business profile, ICP, offer architecture, sequencing rules, open questions, decision archaeology, change log, or any other shape that fits the client). The README is the authoritative source of client context.
- Cluster summaries for clusters relevant to the client's profile (e.g., for a marketing client, the marketing cluster; for an app-building client, the app-building cluster)
- Operator's `_strategic-decisions/` folder contents at `04_projects/clients/_active/_strategic-decisions/` (operator-discipline context that affects client work across all clients; e.g., three-track migration playbook, visual social proof capture model, client onboarding patterns)
- Relevant tactic notes from contributing clusters (filtered by client-relevance; don't dump unrelated tactics)
- Master primer for shared vocabulary

**Output structure (high-level; detailed templates in Chunk 4):**
- Client context summary (compressed restatement of relevant README sections; what the client wants, what their current state is, what constraints apply)
- Evidence base used (which clusters synthesized, why each is relevant to this client)
- Tactical recommendations (specific actions filtered by client-relevance per profile)
- Sequencing (what to do first, second, third; respects client's stated sequencing rules from README if present)
- Decision points operator/client needs to resolve (open questions from README surfaced if relevant; new questions surfaced by synthesis)
- Risks and constraints (operator-discipline precedents that bound the recommendations; client-specific constraints from README)
- Deliverable shape (if synthesis is intended as input to a client-deliverable document, surface the shape that document should take)

**Filing destination:** `04_projects/clients/_active/<client-slug>/client-synthesis-<client-slug>-<topic>-<date>.md`

Filed in the client's own folder. The client's folder becomes the operational home for all artifacts related to that client (README + synthesis + any operator-internal notes + any client-deliverable drafts).

**Discipline-specific notes:**
- **README prerequisite is hard.** No README → synthesis blocked. Suggested remediation surfaced to operator: create README first.
- **Read the full README.** Don't assume field structure; don't skip sections. Operator's README format may evolve; synthesis adapts to whatever's there.
- **README sections like "Open questions" and "Sequencing rules" (if present) are load-bearing.** They tell synthesis what to drive toward and what to defer. If README has these sections, synthesis should respect them.
- **Evidence-filtering is operator-discipline.** A marketing client doesn't need substrate-cluster evidence; a substrate-research client doesn't need marketing cluster evidence. Synthesis filters by client-relevance per profile.
- **Cross-reference `_strategic-decisions/` folder.** Operator's accumulated cross-client discipline (e.g., three-track migration playbook) applies to client work; synthesis should respect those precedents.
- **The synthesis is operator-facing first, client-facing second.** Even if intended for client delivery, the synthesis is operator's strategic working document. The client-deliverable that may eventually ship is a downstream artifact (drafted from the synthesis, not equal to the synthesis).

**Phase B exemplar:** As of this skill's creation (2026-05-13), no client-driven synthesis exists in vault that this author is aware of (operator's structured client work is new as of 2026-05-13). The first client-driven synthesis will likely be for EV Electric Services or S&H Contracting — both have active READMEs.

### Cross-cluster vs client-driven distinction

Both cross-cluster synthesis and client-driven synthesis may pull from multiple clusters. The distinguishing factor is the ANCHOR:

- **Cross-cluster synthesis anchor:** operator-strategic question (e.g., "what does evidence collectively suggest for marketing-PM agent worker repertoire?"). The anchor is operator's own strategic concern. Filing: `_meta/synthesis/`.
- **Client-driven synthesis anchor:** specific client + their stated outcome (e.g., "based on EV Electric Services and their 90-day plan in README, drive them toward booking 30 jobs"). The anchor is the client's profile and outcome. Filing: client's own folder.

If operator's request anchors on a strategic question but mentions a client incidentally (e.g., "what does the evidence say about local SEO, given my client work background"), it's cross-cluster shape. If operator's request anchors on a specific client's outcome but mentions strategic questions incidentally (e.g., "synthesize for EV Electric Services using whatever cluster evidence applies"), it's client-driven shape.

Multi-anchor cases (genuinely both operator-strategic AND client-deliverable) should surface to operator at Stage 2 for clarification. Ask: "Is the primary anchor operator-strategic (cross-cluster shape) or client-deliverable (client-driven shape)?" Default to client-driven if operator surfaces a specific client outcome; default to cross-cluster if operator surfaces a strategic question without specific client deliverable in mind.

## Mode 3 elicitation at invocation

Operator's invocation request may not explicitly name the shape. Skill 3's Stage 2 analysis figures out the shape from request phrasing. This section documents the elicitation logic.

### Shape signals in operator's request

**Cluster signals:**
- Names a specific cluster: "the marketing cluster," "the substrate sources," "the content/video-intelligence work"
- Names a domain folder: "everything in 03_domains/marketing/"
- Asks to consolidate vault work in one specific area without strategic framing

**Pattern signals:**
- Names a specific pattern: "the agent-substrate-as-MCP-backend pattern," "cross-creator-counting precedent application"
- Asks to consolidate evidence on a specific architectural commitment
- References a specific tactic note: "synthesize tactic-context-engineering-discipline"

**Cross-cluster signals:**
- Asks an operator-strategic question that spans clusters: "what does evidence collectively suggest for X"
- Names multiple clusters explicitly: "marketing + content + app-building"
- References operator-strategic anchor: "given my Goal A decisions, what do clusters A and B suggest"

**Client-driven signals:**
- Names a specific client (by slug, name, or business): "client EV Electric Services," "client Z," "for [business name]"
- References client-deliverable shape: "strategy for," "roadmap for," "plan to deliver X for"
- References client outcome: "get them their stated outcome," "drive them toward Y result"

### Ambiguous request handling

If the request fits multiple shapes or fits none clearly:

**Multi-shape candidate:** Surface to operator at Stage 2 with explicit "this could be shape A or shape B" reasoning, and ask operator to clarify. Don't guess; ask. Example: "Synthesize the marketing cluster for client X" could be cluster synthesis OR client-driven synthesis depending on intent.

**No-clear-shape:** Surface to operator that the request doesn't fit any standard shape, and ask for clarification on shape + scope + intent. Don't fabricate a shape that doesn't fit.

**Mismatched signals:** If request names a cluster but asks an operator-strategic question (looks like cluster signal + cross-cluster signal mixed), surface the mismatch and ask operator which shape they want. Example: "synthesize the marketing cluster to inform my client-acquisition strategy" — is this cluster synthesis OR cross-cluster synthesis with marketing as one input?

### Stage 2 elicitation discipline

The Stage 2 proposal should:

- Quote the operator's verbatim request at the top of the proposal
- Show shape reasoning explicitly so operator can validate the shape match
- Propose ONE primary shape (not multiple) unless the request is genuinely ambiguous, in which case surface the ambiguity as a clarifying question rather than producing a multi-shape proposal
- For client-driven shapes: confirm the client README path explicitly so operator can verify the right client is being synthesized
- For cross-cluster shapes: confirm the anchor question so operator can verify the synthesis will drive toward the right strategic outcome

## Reference files

The actual content this skill operates on lives outside the skill folder:

- **Master primer:** `~/workspace/second-brain/_meta/primers/primer-synthesis-vocabulary-and-concepts.md`
- **Reading guide folder:** `~/workspace/second-brain/_meta/primers/readings/`
- **Synthesis folder (cross-cluster):** `~/workspace/second-brain/_meta/synthesis/`
- **Domain folder (cluster synthesis):** `~/workspace/second-brain/03_domains/<cluster>/`
- **Pattern folder (pattern synthesis):** `~/workspace/second-brain/05_shared-intelligence/patterns/`
- **Client folder (client-driven synthesis):** `~/workspace/second-brain/04_projects/clients/_active/<client-slug>/`
- **Scoring rubric:** `~/workspace/second-brain/_meta/scoring-rubric.md`
- **Skill 1 (VIS extraction):** `~/workspace/skills/vis-extraction/SKILL.md`
- **meta-document-primer skill:** `~/workspace/skills/meta-document-primer/SKILL.md`
- **plain-language-translation skill:** `~/workspace/skills/plain-language-translation/SKILL.md`

Read these as needed. The master primer is canonical for shared vocabulary across syntheses; this SKILL.md is the orchestration layer that drives synthesis production and invokes the two companion skills.
